name: Django Github Action
on: workflow_dispatch
#on:
#  push:
#    branches:
#      - main
#      - MP/django-github-action
#  pull_request:
#    types: [ review_requested ]
#    branches:
#      - main

jobs:
  build:
    runs-on: ubuntu-20.04
    services:
      postgres:
        image: postgres:14-alpine
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: db_test
        ports:
          - 5432/tcp
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install --user pipenv
          pipenv install

      - name: Lint with Flake8
        run: |
          pipenv run flake8 .

      - name: Executing testcases
        env:
            SECRET_KEY: 55b670aa942e747e4aaa275128207dc0d5d98c7f4ff09ea87a42c02fffcd71bfd3f87d78a27fac3a4dd1d7ae7d7217658a22
            DATABASE_URL: psql://postgres:postgres@localhost:${{ job.services.postgres.ports[5432] }}/db_test
            CORS_ALLOWED_ORIGINS: "http://localhost:8080,https://bta-service.onrender.com,https://bus-tracking-app.onrender.com"
        run: |
          pipenv run coverage run -m pytest -vv

      - name: Test Coverage report
        run: |
          pipenv run coverage report
