name: Django Tests

on:
  push:
    branches:
      -MP/setup-github-action
  pull_request:
    branches:
      -main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install --user pipenv
        pipenv install
    - name: Test with pytest
      run: |
        pipenv run pytest -vv
    - name: Coverage report
      run: |
        pipenv run coverage run -m pytest
        pipenv run coverage report
